action: train
coco_data_path: /home/zenn/data/cocodataset/train
coco_data_path_test: /home/zenn/data/cocodataset/test
coco_data_path_train: /home/zenn/data/cocodataset/train
coco_data_path_val: /home/zenn/data/cocodataset/val
decoder_model_path: /home/zenn/MomentAlignment/models/decoder_1_25_6_state_dict.pth
do_validation: false
encoder_model_path: /home/zenn/MomentAlignment/models/encoder_1_25_6_state_dict.pth
epoch_saving_interval: 1
epochs: 100
feature_map_batch_size: 4
image_saving_interval: 200
image_saving_path: /home/zenn/MomentAlignment/experiments
imsize: 512
lambda_1: 0
lambda_2: 1
loader: no_norm
lr: 0.0001
model: MomentAlignment
model_dir: /home/zenn/StyleTransfer_test_data/torchvision_models
model_saving_path: /home/zenn/MomentAlignment/experiments
moment_mode: 5
painter_by_numbers_data_path: /home/zenn/data/painter-by-numbers/train
painter_by_numbers_data_path_test: /home/zenn/data/painter-by-numbers/test
painter_by_numbers_data_path_train: /home/zenn/data/painter-by-numbers/train
painter_by_numbers_data_path_val: /home/zenn/data/painter-by-numbers/val
pretrained_model_path: /home/zenn/MomentAlignment/experiments
step_printing_interval: 5000
tensorboardX_path: /home/zenn/MomentAlignment/experiments/
unloader: none
url: https://download.pytorch.org/models/vgg19-dcbb9e9d.pth
use_pretrained_model: false
validation_interval: 50000
